version: 2
jobs:
  one:
    build:
      docker:
        - image: circleci/node:11.2.0

      worling_directory: ~/repo

      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: yarn install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run: yarn test

        - run: yarn build

#workflows:
#  version: 2
#  one_and_two:
#    jobs:
#      - one
